### ISSUE TITLE
ImportError when test name is too long

### ISSUE THREAD

**Issue by josh-browning** [KeyWeeUsr/KivyUnitTest#1]
I have a kivy project stored on my machine at /Users/............../Personal/grocery (my name .-ed out, but with the right number of .s), and my unit tests are stored in this project in the tests folder.  I had one test called 'test_recipe_availability.py' (so the full file path is /Users/............../Personal/grocery/tests/test_recipe_availability.py) and when I run `python -m kivyunittest --folder tests` I get the following error:

    python -m kivyunittest --folder 'tests'
    ======================================================================
    | test_recipe_availabilit                                        LOG |
    ======================================================================
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/joshuabrowning/anaconda/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
        module = __import__('.'.join(parts_copy))
    ImportError: No module named test_recipe_availabilit

When I rename the test to test_recipe_avail.py, everything works fine.

**Comment by KeyWeeUsr** [comment]
I have no limitation set there, but I think it's the Windows that interferes. There's a limitation for the length of a filepath and I think you might have reached it. Try to put it into e.g. `C:\` and keep the long name for your test, it should work.

Edit: Definitely not the package's issue as I have a little bit longer name [right here](https://github.com/KeyWeeUsr/KrySA/blob/master/krysa/tests/test_tasks_plot_lineplot.py), only the path I use has together (with `\`s) 86 characters. Windows has a limit on [256](http://stackoverflow.com/q/265769/5994041) characters or maybe a little bit more in newer versions for a single filename.
