### ISSUE TITLE
Test fail silently

### ISSUE THREAD

**Issue by AndreMiras** [KeyWeeUsr/KivyUnitTest#2]
I'm giving KivyUnitTest (0.1.3) a try for my [PyWallet](https://github.com/AndreMiras/PyWallet) application.

If the test contains some error, it still prints a success message.

Example in the `kivyunittest/test_text.py` example.
If you introduce an "assert False" the first line or if the a module import is not correct.
The output will still be:
```
self.modules: ['test_text']
Ran 1 test in 0.049s
SUCCESS!
```
I would expect the test to fail instead and have the stack trace.
I haven't looked deeply yet, but this issue seems to be by design. It seems that we run test in a subprocess and parse the output result.

**Comment by KeyWeeUsr** [comment]
This appears to be a rather nasty bug because first I thought that the `loadTestsFromName` just imports the class, therefore this would work:

```python
class MyCase(unittest.TestCase):
    assert False
```

but then I got to this part:

```python
import os
import sys
import time
import os.path as op
from functools import partial
# assert False
from kivy.clock import Clock
# assert False
```

which rather surprised me with dirty tricks playing on me. It won't thrown an error sooner than you import something from Kivy although I'm not sure why actually.

For now I can only recommend you to use it this way and I'll leave the issue open if someone has an idea because it's definitely a bug, however I'm not sure on which side.

```python
import kivy  # first line in the file
assert False  # fails properly
import unittest  # if you care about running the test as "python test.py"

<the rest of the file>
```

**Comment by KeyWeeUsr** [comment]
Closed by https://github.com/KeyWeeUsr/KivyUnitTest/commit/1296b659b4b5658e03f33838e997d9612abce71a#diff-ca3657fe35120f82047527c53edcefa6R133. The import was moved to the internal call of the new interpreter. It's still kind of there, but hidden, however a common user shouldn't encounter it anymore.

**Comment by AndreMiras** [comment]
In fact we're almost there, but it's not completely solved in my setup because...
```
if line.startswith('Traceback'):
```
The traceback start with a leading white space even though I'm running Python 2.7.12. Wait, that's not all.
It only has a leading white space when I put an `assert False` straight after the `import kivy`. But if I put it within the `run_test()` it will NOT have the leading white space.

In fact that's probably a slightly different issue (even though it's somewhat related to this issue).
Do you want me to create a dedicated ticket to describe it?

**Comment by KeyWeeUsr** [comment]
@AndreMiras Thanks for noticing. It isn't a different issue, it's just that Python's `Traceback` output for some reason is screwed up. I'm not sure if I did that, but I noticed the change between raw py2 and py3 tracebacks, so it might be that the transition from 2 to 3 version added whitespace only to some places for providing the traceback and at the same time I did a quite stupid check for the traceback presence itself. It should be ok now wherever you put the error.

**Comment by AndreMiras** [comment]
Great, tested and it works perfectly!
Actually even if I `assert False` or `import does_not_exist` before `import kivy` the test will now fail as expected.
Can't wait for the official PyPi release :)
By the way I wanted to have a little chat the other day, regarding some question/suggestions, but I didn't find any way to contact you. I checked for gitter, google group, stackoverflow, your webpage http://badida.sk/ ...

**Comment by KeyWeeUsr** [comment]
I mostly hang out on Freenode's IRC channels #kivy and #kivy-dev and you can find my email even on the [Kivy webpage](https://kivy.org/#aboutus), or in the source I publish either as a GitHub's "alias" (it forwards the mails to the real address) or I have the email somewhere in the top parts of scripts/licenses/... of my personal projects (even in this particular project) :)
