### ISSUE TITLE
Provide a --start-directory argument

### ISSUE THREAD

**Issue by AndreMiras** [KeyWeeUsr/KivyUnitTest#3]
Similarly to was is available for the python unittest module, it would be nice to have a `--start-directory` argument that fills the Python path, rather than hardcoding it in each tests.

**Comment by KeyWeeUsr** [comment]
Do you mean this part?

```python
main_path = op.dirname(op.dirname(op.abspath(__file__)))
sys.path.append(main_path)
```

if yes, then yeah, it's quite a nice feature to have. I'll look into that soon, or if you have some changes then feel free to make a PR :)

**Comment by AndreMiras** [comment]
Yes this is exactly what I meant. Happy you also agree.
Yes I would definitely do a PR, if I make the change.

**Comment by KeyWeeUsr** [comment]
Closed with https://github.com/KeyWeeUsr/KivyUnitTest/commit/a795df664e4755b8397208a9c57affca2a8e5ef9.

**Comment by AndreMiras** [comment]
Awesome, thank you!

**Comment by AndreMiras** [comment]
Please check the comments I've added to https://github.com/KeyWeeUsr/KivyUnitTest/commit/a795df664e4755b8397208a9c57affca2a8e5ef9#diff-ca3657fe35120f82047527c53edcefa6R47 and let me know what do you think.
It looks like a regression.

**Comment by KeyWeeUsr** [comment]
@AndreMiras You might want to try again with the latest changes. It should work correctly now. Release soon with some rewrite in the guide for the more advanced input handling.

**Comment by AndreMiras** [comment]
Fixed after running from latest master, well done!
```
pip install --upgrade https://github.com/KeyWeeUsr/KivyUnitTest/archive/master.zip
```
